# Code generated by font_to_py.py.
# Font: Dot Matrix Bold.ttf Char set: 0123456789
# Cmd: third_party/font_to_py/font_to_py.py third_party/fonts/Dot Matrix Bold.ttf 10 -c 0123456789 -x src/assets/dot_matrix_seconds.py
version = '0.33'

def height():
    return 7

def baseline():
    return 7

def max_width():
    return 7

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return False

def min_ch():
    return 48

def max_ch():
    return 63

_font =\
b'\x06\x00\x70\xd8\x18\x30\x60\x00\x60\x07\x00\x78\xcc\xcc\xcc\xcc'\
b'\xcc\x78\x05\x00\x60\xe0\x60\x60\x60\x60\xf0\x07\x00\x78\xcc\x0c'\
b'\x78\xc0\xc0\xfc\x07\x00\x78\xcc\x0c\x38\x0c\xcc\x78\x07\x00\x1c'\
b'\x3c\x6c\xcc\xfc\x0c\x0c\x07\x00\xfc\xc0\xf8\x0c\x0c\xcc\x78\x07'\
b'\x00\x7c\xc0\xf8\xcc\xcc\xcc\x78\x07\x00\xfc\x0c\x18\x30\x60\x60'\
b'\x60\x07\x00\x78\xcc\xcc\x78\xcc\xcc\x78\x07\x00\x78\xcc\xcc\x7c'\
b'\x0c\xcc\x78'

_index =\
b'\x00\x00\x09\x00\x12\x00\x1b\x00\x24\x00\x2d\x00\x36\x00\x3f\x00'\
b'\x48\x00\x51\x00\x5a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'\
b'\x00\x00\x63\x00'

_mvfont = memoryview(_font)
_mvi = memoryview(_index)
ifb = lambda l : l[0] | (l[1] << 8)

def get_ch(ch):
    oc = ord(ch)
    ioff = 2 * (oc - 48 + 1) if oc >= 48 and oc <= 63 else 0
    doff = ifb(_mvi[ioff : ])
    width = ifb(_mvfont[doff : ])

    next_offs = doff + 2 + ((width - 1)//8 + 1) * 7
    return _mvfont[doff + 2:next_offs], 7, width
 
