#!/usr/bin/env python3
# Copyright (c) 2023 Tom Ward
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""Writes the module carrying the tokens one firmware image was built with.

A display given away as a present should ask for the wifi and nothing else, so
its tokens travel in the firmware rather than being typed into the setup page.
The manifest freezes what this writes; config.py reads it last, after
config.json and the environment, so a build with no .env bakes empty strings
and changes nothing.

Both values are copied verbatim, leaving config.py the only reader of what a
Grafana header means.

Not a secret store: frozen strings are plain text in the image, and `strings
firmware.uf2` prints them. docs/build-your-own.md says what that means.

  tools/write_baked.py build/baked.py
"""

import os
import sys

# What the module calls each token, and the .env variable it comes from.
_BAKED = {
    'RTT_TOKEN': 'RTT_TOKEN',
    'OTEL_HEADERS': 'OTEL_EXPORTER_OTLP_HEADERS',
}

_TEMPLATE = '''\
# Generated by tools/write_baked.py. Not checked in.
"""Tokens built into this firmware. Empty unless the build had a .env."""

{body}'''


def module_text(values: dict) -> str:
  body = ''.join(
      '{} = {!r}\n'.format(name, values.get(name) or '') for name in _BAKED
  )
  return _TEMPLATE.format(body=body)


def write(path: str, values: dict) -> bool:
  """Writes the module, reporting whether that changed anything.

  Left alone when it would be written identically: the build recompiles every
  frozen module when one of them is newer, so rewriting it each time would
  turn every incremental firmware build back into a slow one.
  """
  text = module_text(values)
  try:
    with open(path) as f:
      if f.read() == text:
        return False
  except OSError:
    pass

  with open(path, 'w') as f:
    f.write(text)
  return True


def describe(values: dict) -> str:
  """What was baked, for the build to print. Never what it was.

  A build that quietly baked nothing looks like one that worked, until the
  display asks a family member for an API token.
  """
  baked = [name for name in _BAKED if values.get(name)]
  if not baked:
    return 'nothing, so the setup page will ask for the tokens'
  return ', '.join('{} ({} chars)'.format(n, len(values[n])) for n in baked)


def main() -> int:
  if len(sys.argv) != 2:
    print(__doc__)
    return 2

  values = {name: os.environ.get(var, '') for name, var in _BAKED.items()}
  changed = write(sys.argv[1], values)
  print(
      '  Baked in: {}{}'.format(
          describe(values), '' if changed else ' (unchanged)'
      )
  )
  return 0


if __name__ == '__main__':
  sys.exit(main())
